title: Michelle De Luna
description: An AOS 204 final project dedicated to exploring the Amundsen Sea Low (ASL) and its relation to additional Southern Hemisphere modes of variability (MOVs). 
logo: /assets/IMG/ASL_study_area_with_overall_avg.png
show_downloads: true
theme: jekyll-theme-minimal
