title: Michelle De Luna
description: An AOS C111/204 final project dedicated to exploring the Amundsen Sea Low (ASL). 
logo: /assets/IMG/ASL_study_area_with_overall_avg.png
show_downloads: true
theme: jekyll-theme-minimal
